- [迭代器](#迭代器)
  - [遍历与迭代的关系是什么？](#遍历与迭代的关系是什么)
  - [使用`for...of`遍历对象](#使用forof遍历对象)
- [生成器](#生成器)
  - [`return 1;`与`yield 1;`之间是什么区别？](#return-1与yield-1之间是什么区别)
- [promise](#promise)
  - [如何理解 promise 的固化？](#如何理解-promise-的固化)
  - [Promise.resolve()与promise.reject()](#promiseresolve与promisereject)
  - [promise的链式调用](#promise的链式调用)
  - [如何理解状态依赖？](#如何理解状态依赖)
  - [promisefy](#promisefy)
- [async/await](#asyncawait)
  - [执行器](#执行器)

注：学习资料来源-前端小夏老师
## 迭代器

### 遍历与迭代的关系是什么？

为了解释遍历与迭代之间的关系，首先看几个最简单的例子：
```javascript
var arr = [1, 2, 3, 4];
var str = '123';
var obj = { a: 1, b: 2 };

// 遍历数组
for (var i = 0; i < arr.length; i++) {
  console.log(arr[i])
}

arr.forEach(function (item) {
  console.log(item);
});

// 遍历字符串
for (var i = 0; i < str.length; i++) {
  console.log(str[i])
}

// 遍历对象
for (var i in obj) {
  console.log(i, obj[i]);
}

function test() {
  console.log([...arguments]);

}

test(1, 2, 3, 4)
```
以上代码中列出的是JS中很常见的三种数据类型：Array, string, object, 并且列出了遍历这三种数据类型的方法。不同的数据类型会有不同的遍历方法，有没有一种方式能够实现一种统一的数据类型的遍历呢？迭代器的出现就是为了实现所有数据类型的统一遍历。

`Array, Map, Set, TypeArray, arguments, NodeList`这几种类型都是能够实现一步遍历的， 即可以使用`for...of`实现遍历。
```javascript
var arr = [1, 2, 3, 4];
var str = '123';
var obj = { a: 1, b: 2 };

for (let i of arr) {
  console.log(i)  // 正常遍历
}

for (let i of str) {
  console.log(i)  // 正常遍历
}

for (let i of obj) {
  console.log(i)  // Uncaught TypeError: obj is not iterable
}
```
上述代码可以发现，`for...of`能够实现对数组和字符串的遍历，但是对象不能使用`for...of`进行遍历，为什么？

可以打印看一下：
```javascript
var arr = [1, 2, 3, 4];
var str = '123';
var obj = { a: 1, b: 2 };
console.log(arr);
console.log(Object.getPrototypeOf(str));
console.log(obj);
```
可以看到在arr的原型上有一个方法叫：`Symbol(Symbol.iterator)`,str原型上也有这个方法，但是obj上没有。也就是说，原型上部署了这样一个方法的话，就可以使用`for...of`进行遍历。

看一下arr原型上的这个`Symbol(Symbol.iterator)`方法，

```javascript
console.log(arr[Symbol.iterator]())

// Array Iterator {}
//      __proto__: Array Iterator
//          next: ƒ next()
//          Symbol(Symbol.toStringTag): "Array Iterator"
//          __proto__: Object
```
可以看到里面有一个next方法,调用一下试试看：
```javascript
var iter = arr[Symbol.iterator]();
console.log(iter.next());   // {value: 1, done: false}
```
会发现，输出的是一个对象，其中，value表示数组中第0个元素的值，done表示是否完成迭代，上面输出的是false，说明没有完成迭代，还可以继续调用：
```javascript
var iter = arr[Symbol.iterator]();
console.log(iter.next());   // {value: 1, done: false}
console.log(iter.next());   // {value: 2, done: false}
console.log(iter.next());   // {value: 3, done: false}
console.log(iter.next());   // {value: 4, done: false}
console.log(iter.next());   // {value: undefined, done: true}
```
现在可以解释什么是迭代器对象了：`arr[Symbol.iterator]()`就是迭代器对象。可以发现，迭代器对象是有一个next方法的，可以使用next方法实现逐步调用，在逐步调用的过程中返回一个对象，这个对象中包含`value、done`两个属性。

能不能使得对象也能使用`for...of`进行遍历呢？可以。

先来看如何实现一个自定义的迭代器：
```javascript
function makeIterator(arr) {
    var index = 0;
    return {
        next() {
            if (index < arr.length) {
            return { value: arr[index++], done: false }
            }
            return { value: undefined, done: true };
        }
    }
}

var arr = [1, 2, 3, 4];
var iter = makeIterator(arr);
console.log(iter.next());
console.log(iter.next());
console.log(iter.next());
console.log(iter.next());
console.log(iter.next());
```

### 使用`for...of`遍历对象

```javascript
var obj = {
  a: 1,
  b: 2,
  c: 3,
  [Symbol.iterator]() {
    var index = 0;
    let map = new Map();  // 
    map.set('a', 1)
    map.set('b', 2)
    map.set('c', 3)
    // console.log(map);
    return {
      next() {
        // 获取obj的键值对组成的数组
        var mapEntries = [...map.entries()];  // ... 调用的就是for...of方法
        if (index < map.size) {
          return { value: mapEntries[index++], done: false };
        }
        return { value: undefined, done: true };
      }
    }
  }
};

var iter = obj[Symbol.iterator]();
console.log(iter.next());
console.log(iter.next());
console.log(iter.next());
console.log(iter.next());
```

`for..of`的本质：调用`[Symbol.iterator]`迭代器接口，我们已经给obj部署了这个接口，现在就可以使用`for..of`遍历obj了：

```javascript
for (var i of obj) {
  console.log(i);
}
```

小结：遍历与迭代的区别？

遍历：不强调依次，逐个，只要能循环所有的数据，可以一次性将数据抽取出来；

迭代：从目标源依次、逐个抽取的方式来提取数据;  数据结构要保证是_**`有序的, 连续的`**_。比如，Array, Set, Map, arguments,NodeList上是有index的保证有序与连续。

这里就看下NodeList：

hmtl部分：
```html
<div></div>
<div></div>
<div></div>
<div></div>
```
js部分
```javascript
var nodeList = document.getElementsByTagName('div');
console.log(nodeList);
// 0: div
// 1: div
// 2: div
// 3: div
// length:4
// __proto__

for (var i of nodeList) {
  console.log(i);
}
```

通过上述的分析会发现，`Array, Map, Set, TypeArray, arguments, NodeList`这几种类型都能够使用`for...of`实现一步遍历，但是对于object来说并不方便，如果要实现这样的迭代就要像上面一样部署迭代器接口，比较麻烦，那有没有更简单的方法可以生成迭代器对象，让这个迭代器对象能够直接实现遍历？  --- 生成器。所以生成器是为了生成迭代器的。


## 生成器

最简单的生成器形式：
```javascript
function* test() {
    yield 1;
    yield 2;
    yield 3;
    yield 4;
}

var iter = test();
console.log(iter.next());  // {value: 1, done: false}
console.log(iter.next());  // {value: 2, done: false}
console.log(iter.next());  // {value: 3, done: false}
console.log(iter.next());  // {value: 4, done: false}
console.log(iter.next());  // {value: undefined, done: true}

for (var i of iter) {
  console.log(i);
}
```

具体来看下是如何调用的：
```javascript
function* test() {
    console.log(1);
    yield 1;
    yield 2;
    yield 3;
    yield 4;
}

var iter = test();
// console.log(iter);
```

```javascript
function* test() {
    console.log(1);
    yield 1;
    console.log(2);
    yield 2;
    yield 3;
    yield 4;
}

var iter = test();
console.log(iter.next());
// 1
// {value: 1, done: false}
console.log(iter.next());
// 2
// {value: 2, done: false}
```
第一段代码，没有任何内容输出，第二段代码调用了next方法之后输出了1，并且输出了`{value: 1, done: false}`对象，也就是说，在调用next之前，生成器函数并不会执行，每调用一次next方法，就会执行到yield之后。实际上，yield能够中断函数，有点像return，但是又不一样。

```javascript
function* test() {
    console.log(1);
    return 1;
}

var iter = test();
console.log(iter);
console.log(iter.next());
```
将生成器函数中的yield换成return，发现生成器函数也没有执行，返回的是一个迭代器对象(里面有next方法)，也就是说，生成器函数中的返回值并不由return来决定，而是由yield来决定，当前`return 1`这个语句还没有走到，在执行next方法之后才会继续往下走，走到return。

### `return 1;`与`yield 1;`之间是什么区别？

如果是`return 1;`上述代码执行得到对象`{value: 1, done: true}`，如果是`yield 1;`上述代码执行得到对象`{value: 1, done: false}`，也就是说在执行一次next的时候，执行到第一个yield之后，此时它并不知道这个yield后面还有没有下一个yield，所以输出的对象中done属性值为false，需要进一步执行next方法，会得到`{value: undefined, done: true}`,抽取结束。再换成`return 1;`，执行两次next方法得到的分别是：`{value: 1, done: true}` 和`{value: undefined, done: true}` 。 在生成器函数中，我们一般不会手动return。

next方法是可以传递参数的：
```javascript
function* test() {
  let value1 = yield 1;
  console.log(value1);
}

var iter = test();
console.log(iter.next('one'));
console.log(iter.next('two'));
```
上述代码要想走到`console.log(value1);`这条语句，就要执行两次next方法，如果两次都传递一个不同的参数，会发现打印出来的是第二次执行next时传递的参数two，而不是第一次执行next时传递的one。

```javascript
function* test() {
  
  let value1 = yield 1;
  console.log(value1);
  let value2 = yield 2;
  console.log(value2);
  let value3 = yield 3;
  console.log(value3);
  let value4 = yield 4;
  console.log(value4);
}

var iter = test();
console.log(iter.next('one'));
console.log(iter.next('two'));
console.log(iter.next('three'));
console.log(iter.next('four'));
console.log(iter.next());
```
next传递地参数是如何输出的？`yield 1`的返回值对应的是`next 2(表示第二次执行next方法)`传递进来的参数，`yield 2`的返回值对应的是`next 3`传递进来的参数，`yield 3`的返回值对应的是`next 4`传递进来的参数，`yield 4`的返回值对应的是`next 5`传递进来的参数。这样的接收形式看起来比较混乱，有没有一种方式能够使得yield产出的值与next的执行是一一对应的？这就很像`async/await`了。`async函数 = 生成器函数 +  执行器函数`。

实现：使用`for...of`遍历一个对象。
```javascript
var obj = {
  a: 1,
  b: 2,
  c: 3,
  [Symbol.iterator]: function* () {
    var index = 0;
    let map = new Map();
    map.set('a', 1)
    map.set('b', 2)
    map.set('c', 3)
    console.log(map);

    var mapEntries = [...map.entries()];
    
    while (index < mapEntries.length) {
      yield mapEntries[index++]
    }

  }
};

for (var i of obj) {
  console.log(i);
}
```

## promise

1. JQ中ajax的3种写法 - 了解

```html
<script src="https://cdn.bootcdn.net/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

<script>

  // 1
  $.ajax({
    url: 'https://jsonplaceholder.typicode.com/posts',
    type: 'GET',
    dataType: 'JSON',
    success: function (data) {
      console.log(data);
    }
  })

  // 2
  var ajax1 = $.ajax('https://jsonplaceholder.typicode.com/posts');

  ajax1.done(function (data) {
    console.log(data);
  }).fail(function (err) {
    console.log(err);
  })

  // 3
  var ajax2 = $.ajax('https://jsonplaceholder.typicode.com/posts');

  ajax2.then(function (data) {
    console.log(data);
  }, function (err) {
    console.log(err);
  })
</script>
```

2. 回调地狱 - 以Nodejs实现文件读取为例

什么是回调函数： 作为函数A的形参的函数。
```javascript
let fs = require('fs');

fs.readFile('./name.txt', 'utf-8', function (err, data) {  // 回调函数
  fs.readFile(data, 'utf-8', function (err, data) {  // 回调函数
    fs.readFile(data, 'utf-8', function (err, data) {  // 回调函数
      if (err) {
        return;
      }
      console.log(data);
    }) 
  }) 
});
```
其中，上述采用异步方式进行文件内容读取，`name.txt`文件中存储的是下一个需要找的文件地址`/.number.txt`，文件`number.txt`中存储的内容是数字`100`，需要通过上述层层嵌套回调函数的形式找到number.txt中存储的数字。
随着嵌套层数越深，就形成了回调地狱，在错误捕获的时候很难查到是哪一步出现的错误。

3. promise注册回调函数的形式读取文件

```javascript
let fs = require('fs');

function readFile(pathname) {
  return new Promise(function (resolve, reject) { // executor （执行器函数）
    console.log(1);
    fs.readFile(pathname, "utf-8", function (err, data) {
      if (err) {
        reject(err);
        return;
      }
      resolve(data);
    });
  })
}

// 异步任务的完成与否取决于当前 promise 的状态;
let promise = readFile('./name.txt');
// pending  进行中
// fulfilled  已完成
// rejected 已失败;
promise.then(function (data) {
  console.log('success' + data);
}, function (err) {
  console.log(err);
})
```
- promise状态不受外界影响
- promise的固化：一旦 promise 状态变化后就不可再更改

### 如何理解 promise 的固化？

```javascript
let fs = require('fs');
function readFile(pathname) {
  return new Promise(function (resolve, reject) {
    fs.readFile(pathname, 'utf-8', function (err, data) {
      if (err) {
        reject(err);
        return;
      }
      resolve(data);
    });
  })
}

let promise = readFile('./name.txt');

promise.then(function (data) {
  console.log('第一次调用' + data);
  promise.then(function (data) {
    console.log('第二次调用' + data);
    promise.then(function (data) {
      console.log('第三次调用' + data);
    })
  })
})

// => 
// 第一次调用./number.txt
// 第二次调用./number.txt
// 第三次调用./number.txt
```
第二次和第三次调用拿到的数据都是第一次调用成功时拿到的data。

```javascript
let fs = require('fs');
function readFile(pathname) {
  return new Promise(function (resolve, reject) {
    fs.readFile(pathname, 'utf-8', function (err, data) {
      if (err) return;
      reject(data);  // 文件读取成功，promise由pending变为rejected状态
    });
  })
}

let promise = readFile('./name.txt');

promise.then(function (data) {
  console.log('第一次调用' + data);
}, function (err) {
  console.log(err);
  promise.then(function () {}, function (err) {
    console.log('第二次调用' + err)
    promise.then(function () {}, function (err) {
      console.log('第三次调用' + err)
    })
  })
})

// => 
// ./number.txt
// 第二次调用./number.txt
// 第三次调用./number.txt
```
上述代码，文件读取成功，promise由pending变为rejected状态，.then时只能 在失败的回调函数中 拿到读取的文件内容。

### Promise.resolve()与promise.reject()

> Promise这两个静态方法调用后得到的是完成态的promise, 也就是说可以直接在promise实例的成功态或者失败态回调函数中拿到成功或失败的信息。

```javascript
let p1 = Promise.resolve(1);
let p2 = Promise.reject(2);

p1.then(function (data) {
  console.log(data);
})

p2.then(function () {}, function (err) {
  console.log('err' + err)
})

//
p2.catch(function (err) {
  console.log('err' + err)
})
```

thenable对象怎么理解？看下面代码：

```javascript
let obj = {
  then(resolve, reject) {
    resolve(11)
    // reject(12)
  }
}

let p1 = Promise.resolve(obj);

p1.then(function (data) {
  console.log(data);
}, function (err) {
  console.log(err)
})
```

```javascript
let obj = {
  then(resolve, reject) {
    reject(12)
  }
}

let p1 = Promise.resolve(obj);

p1.then(function (data) {
  console.log(data);
}, function (err) {
  console.log(err)
})
```
使用`Promise.resolve()`, 当去绑定一个对象的参数为`thenable`对象的时候，它会默认调用对象的then方法，通过then来改变promise的状态。then方法里面resolve的值就是得到的promise回调函数中获取到的值，如果then中是resolve，promise就变成了成功态，如果then中是reject，promise实例就变成了失败态。但是`Promise.reject(obj)`不能默认调用obj的then方法：

```javascript
let obj = {
  then(resolve, reject) {
    reject(12)
  }
}

let p1 = Promise.reject(obj);  // 不会默认调用obj中的then方法

p1.then(function (data) {
  console.log(data);
}, function (err) {
  console.log(err)  // 
})
```

练习：
```javascript
Promise.resolve().then(function () {
  console.log('promise1');  
  setTimeout(() => {
    console.log('setTimeout2');
  }, 0)
})

setTimeout(() => {
  console.log('setTimeout1');  
  Promise.resolve().then(function () {
    console.log('promise2');
  })
}, 0)
```

### promise的链式调用

> promise的链式调用，会返回一个普通值或者一个promise对象

```javascript
let p1 = new Promise((resolve, reject) => {
  resolve(1);
})

console.log(p1.then(res => console.log(res)));  

// Promise {<pending>}
//   __proto__: Promise
//   [[PromiseState]]: "fulfilled"
//   [[PromiseResult]]: undefined

// 1
```

```javascript
let p1 = new Promise((resolve, reject) => {
  resolve(1);
})

p1.then(res => console.log(res))  // Promise.resolve(undefined);
  .then(res => console.log(res + 1))
  .then(res => console.log(res + 1))
```
采用链式调用的时候，后一个的状态是由前一个成功或者失败回调函数的返回值 决定的，上述代码中第一个`.then`的成功回调函数没有return，默认返回值为undefined,如果是undefined，它会调用`Promise.resolve(undefined);`,所以，现在的状态是成功态， 在调用第二个`.then`的时候成功 回调中接收到的res就是undefined，`undefined + 1 => NaN`，这个成功回调的返回值依然是默认值undefined，后面`.then`的调用就与刚才解析的过程一致了。所以最终输出结果为：`1  NaN  NaN`。

```javascript
let p1 = new Promise((resolve, reject) => {
  resolve(1);
})

p1.then(res => res + 1)  // 有返回值 -> Promise.resolve(2);
  .then(res => res + 1)
  .then(res => { console.log(res + 1) })
```

如果回调函数的返回值也是一个promise：
```javascript
let p1 = new Promise((resolve, reject) => {
  resolve(1);
})

p1.then(res => new Promise((resolve, reject) => {
  resolve(2);
}))
  .then(function (res) {
    console.log(res);  // 2
  })
```

```javascript
let p1 = new Promise((resolve, reject) => {
  resolve(1);
})

p1.then(res => new Promise((resolve, reject) => {
  reject(2);
}))
  .then(null, function (err) {
    console.log(err) // 2
  })
```
所以，不管是第一次调用`.then`时回调函数中的返回值是普通值还是一个promise，都可以看做是一个 promise，因为如果是返回的普通值，会被用`Promise.resolve()`进行包装，也是形成了一个具有完成态的promise对象。

区分：
```javascript
let p1 = new Promise((resolve, reject) => {
  setTimeout(() => {
    resolve(10)
  }, 1000)
})

// 1. 
p1.then(res => { console.log(res + 1); return res + 1 });
p1.then(res => { console.log(res + 1); return res + 1 });
p1.then(res => { console.log(res + 1); return res + 1 });

// 2. 
p1.then(res => { console.log(res + 1); return res + 1 })
  .then(res => { console.log(res + 1); return res + 1 })
  .then(res => { console.log(res + 1); return res + 1 })
```
第一种：1s后打印3次11。

第二种：1s后打印11，12，13。

### 如何理解状态依赖？

```javascript
const p1 = new Promise((resolve, reject) => { });
const p2 = new Promise((resolve, reject) => {
    resolve(p1);
})
```
p2的状态依赖于p1的状态，也就是说如果p1的状态确定了，即使在p2中`resolve(p1)`也不能改变

```javascript
const p1 = new Promise((resolve, reject) => {
  setTimeout(() => {
    reject('error');
  }, 3000)
})
const p2 = new Promise((resolve, reject) => {
  setTimeout(() => {
    resolve(p1);
  }, 1000)
})

p2.then(res => console.log(res + ' resolve'))
  .catch(err => console.log(err + ' reject'));
```
上述代码的执行过程是这样的：先执行同步代码，注册两个定时器的回调函数，当时间到达1s的时候，执行p2中对应定时器的回调函数，此时p2的状态为成功态，但是此时p1的状态并不知道，3s时p1状态变为失败态，所以最终p2的状态是失败态，由catch捕获输出。所以，这样的嵌套，p2的状态完全依赖于p1的状态，不存在中间过渡的过程，直接依赖于3s后p1的状态。

### promisefy

```javascript
let fs = require('fs');

fs.readFile('./name.txt', 'utf-8', (err, data) => {
  fs.readFile(data, 'utf-8', (err, data) => {
    fs.readFile(data, 'utf-8', (err, data) => {
      console.log(data);
    })
  })
})
```
还是之前读取文件的案例：`name.txt`文件中存储的是一个文件路径即：`./number.txt`，`number.txt`中存储的也是一个路径即：`./score.txt`, `score.txt`文件中存储的是数字10。可以使用上述回调函数嵌套回调函数的方式读取到数字10，如果嵌套的文件比较多的时候就是回调地狱。

现在尝试使用promise的方式来实现文件的读取：
```javascript
let fs = require('fs');

function readFile(filename) {
  return new Promise((resolve, reject) => {
    fs.readFile(filename, 'utf-8', (err, data) => {
      resolve(data);
    })
  })
}


readFile('./name.txt')
  .then(res => readFile(res))
  .then(res => readFile(res))
  .then(res => console.log(res));
```

进一步，一个更通用的方法：
```javascript
let fs = require('fs');

function promisify(fn) {
  return function (...args) {
    return new Promise((resolve, reject) => {
      fn(...args, (err, data) => {
        if (err) {
          reject(err);
          return;
        }
        resolve(data)
      })
    })
  }
}

let readFile = promisify(fs.readFile);

readFile('./name.txt', 'utf-8')
  .then(res => readFile(res, 'utf-8'))
  .then(res => readFile(res, 'utf-8'))
  .then(res => console.log(res));
```

## async/await

### 执行器

使用前面分析的生成器函数能不能拿到`score.txt`文件中存储的数字10呢？
```javascript
let fs = require('fs');

function promisify(fn) {
  return function (...args) {
    return new Promise((resolve, reject) => {
      fn(...args, (err, data) => {
        if (err) {
          reject(err);
          return;
        }
        resolve(data)
      })
    })
  }
}

let readFile = promisify(fs.readFile);

// 生成器函数
function* read() {
  let value1 = yield readFile('./name.txt', 'utf-8');
  let value2 = yield readFile(value1, 'utf-8');
  let value3 = yield readFile(value2, 'utf-8');
  console.log(value3);
}

// 执行器
let iter = read();
let { value, done } = iter.next();
value.then(val1 => {
  let { value, done } = iter.next(val1);
  value.then(val2 => {
    let { value, done } = iter.next(val2);
    value.then(val3 => {
      iter.next(val3);
    })
  })
})
```

屡清楚执行器的执行逻辑就可以将它封装成一个执行器函数：
```javascript
let fs = require('fs');

function promisify(fn) {
  return function (...args) {
    return new Promise((resolve, reject) => {
      fn(...args, (err, data) => {
        if (err) {
          reject(err);
          return;
        }
        resolve(data)
      })
    })
  }
}

let readFile = promisify(fs.readFile);

// 生成器函数
function* read() {
  let value1 = yield readFile('./name.txt', 'utf-8');
  let value2 = yield readFile(value1, 'utf-8');
  let value3 = yield readFile(value2, 'utf-8');
  return value3;
}

// 执行器函数
function Co(iter) {
  return new Promise((resolve, reject) => {
    let next = function (data) {  // 递归函数
      let { value, done } = iter.next(data);
      if (done) {
        resolve(data);
      } else {
        value.then(val => {
          next(val)
        }, reject)
      }
    }
    next();
  })
}

let promise = Co(read());
promise.then(res => {
  console.log(res)
})
```

上述逻辑就是`async/await`的由来，与下面的代码执行效果相同：
```javascript
let fs = require('fs');

function promisify(fn) {
  return function (...args) {
    return new Promise((resolve, reject) => {
      fn(...args, (err, data) => {
        if (err) {
          reject(err);
          return;
        }
        resolve(data)
      })
    })
  }
}

let readFile = promisify(fs.readFile);


async function readSync() {
  let value1 = await readFile('./name.txt', 'utf-8')
  let value2 = await readFile(value1, 'utf-8');
  let value3 = await readFile(value2, 'utf-8');
  return value3
}

let promise1 = readSync();
promise1.then(function (res) {
  console.log(res);
})
```
比较上述两段代码，发现，实际上是将第一段代码的生成器函数变成了async函数，里面的yield换成await，且async/await本身包含了Co执行器。

最后，可以尝试一下TJ大神封装的co模块：
```javascript
let fs = require('fs');
let co = require('co');

function promisify(fn) {
  return function (...args) {
    return new Promise((resolve, reject) => {
      fn(...args, (err, data) => {
        if (err) {
          reject(err);
          return;
        }

        resolve(data)
      })
    })
  }
}

function* read() {
  let value1 = yield readFile('./name.txt', 'utf-8')
  let value2 = yield readFile(value1, 'utf-8');
  let value3 = yield readFile(value2, 'utf-8');
  return value3;
}

let readFile = promisify(fs.readFile);
let promise = co(read());

promise.then(res => {
  console.log(res);
})
```
